services:
  # Servicio de la base de datos (Postgres)
  db:
    image: postgres:15
    container_name: tp_TD7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp_TD7

    ports:
      - "5439:5432"


volumes:
  postgres_data:
